#!/usr/bin/env python3
"""The table of 128-bit powers of five of Eisel-Lemire (docs/gap-float.md section 3), generated with Python integers and written as a cancho `static`.

    pow5_table.py            write tools/table/pow5.cho
    pow5_table.py --check    regenerate in memory and compare with the file (exit 1 when they differ)

Entry q (-342 <= q <= 308) is the pair (high 64 bits, low 64 bits) of a 128-bit number whose top bit is set:
  q >= 0: 5^q shifted until it has exactly 128 bits (right: the low bits are dropped, i.e. rounded DOWN; left: exact)
  q <  0: floor(2^b / 5^-q) + 1 with z the least number with 2^z >= 5^-q and b = z + 127 for q >= -27 (the quotient has 128 bits: 'rounded up' is exact there)
          and b = 2z + 128 below (shifted right until it has 128 bits: the +1 then makes it an upper bound of the true value)
as in Lemire's script (fast_float, `script/table_generation.py`). Entry q is at words 2*(q+342) (high) and 2*(q+342)+1 (low).
Both words are written as hi32 << 32 | lo32 (the form `cancho fmt` leaves, so that --check also holds after formatting) because a 64-bit literal with the top bit set does not parse."""
import pathlib
import sys

LO, HI = -342, 308


def entry(q):
    if q >= 0:
        p = 5 ** q
        while p < (1 << 127):
            p <<= 1
        while p >= (1 << 128):
            p >>= 1
        return p
    p = 5 ** (-q)
    z = (p - 1).bit_length()  # the least z with 2^z >= 5^-q
    b = z + 127 if q >= -27 else 2 * z + 2 * 64
    c = (1 << b) // p + 1
    while c >= (1 << 128):
        c >>= 1
    return c


def table():
    return [entry(q) for q in range(LO, HI + 1)]


def word(x):
    return f"0x{x >> 32:08x} << 32 | 0x{x & 0xffffffff:08x}"


def render():
    t = table()
    n = 2 * len(t)
    out = [
        "edition 5;",
        "",
        "module pow5;",
        "",
        "// GENERATED by scripts/spikes/float/pow5_table.py -- do not edit. Powers of five as 128-bit numbers for Eisel-Lemire (docs/gap-float.md): entry q",
        "// (-342..308) is the pair (high, low) at 2*(q+342), 2*(q+342)+1.",
        f"static pow5_128: [int] {{",
        f"    let t = alloc_slice[static]({n}, 0);",
    ]
    for i, v in enumerate(t):
        out.append(f"    t[{2*i}] = {word(v >> 64)};")
        out.append(f"    t[{2*i+1}] = {word(v & ((1 << 64) - 1))};")
    out += ["    return t;", "}", "", "// Word `i` of the table: 2*(q+342) is the high word of the power of five q, 2*(q+342)+1 the low word.", "pub fn word(i: int) -> [] int {", "    return pow5_128[i];", "}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parents[3] / "tools" / "table" / "pow5.cho"
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if here.read_text() == text else 1)
    here.write_text(text)
    print(f"{here}: {len(text)} bytes, {HI - LO + 1} entries")
